DROP TABLE IF EXISTS csrs CASCADE;
DROP TABLE IF EXISTS issues CASCADE;

CREATE TABLE csrs (
  csrid INTEGER PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE issues (
  issueid INTEGER PRIMARY KEY,
  csrid INTEGER REFERENCES csrs(csrid) ON DELETE CASCADE NOT NULL
);
