DROP TABLE IF EXISTS csrs CASCADE;
DROP TABLE IF EXISTS issues CASCADE;

CREATE TABLE csrs (
  csrid SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE issues (
  issueid INTEGER PRIMARY KEY
);
